FROM public.ecr.aws/lambda/nodejs:18

WORKDIR /app

RUN yum install -qy python3 make gcc-c++ git
RUN git clone https://github.com/radarlabs/s2.git .
RUN git submodule init
RUN git submodule sync
RUN git submodule update
RUN npm install
RUN npm run build
